# Generated by Django 6.0.3 on 2026-05-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('capacite', models.IntegerField()),
                ('est_occupee', models.BooleanField(default=False)),
            ],
        ),
    ]
