# Generated by Django 6.0.5 on 2026-05-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='pays',
            field=models.CharField(choices=[('maroc', 'Maroc'), ('espagne', 'Espagne'), ('italie', 'Italie'), ('japon', 'Japon'), ('chine', 'Chine')], default='maroc', max_length=20),
        ),
    ]
