# Generated by Django 6.0.5 on 2026-05-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_plat_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
