# Generated by Django 6.0.5 on 2026-05-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_plat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='plat',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='menu.categorie'),
        ),
    ]
