# Generated by Django 6.0.5 on 2026-05-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_categorie_plat_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
    ]
